// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project.Models;

namespace project.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20210510211814_AddedPlacesAndFlightTables")]
    partial class AddedPlacesAndFlightTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("project.Models.Airplane", b =>
                {
                    b.Property<int>("airplaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("airplane_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("businessClassCapacity")
                        .HasColumnType("int")
                        .HasColumnName("business_class_capacity");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("dateOfLastService")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_last_service");

                    b.Property<int>("economyClassCapacity")
                        .HasColumnType("int")
                        .HasColumnName("economy_class_capacity");

                    b.Property<int>("firstClassCapacity")
                        .HasColumnType("int")
                        .HasColumnName("first_class_capacity");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<double>("hoursFlown")
                        .HasColumnType("float")
                        .HasColumnName("hours_flown");

                    b.Property<string>("manufacturer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("productionYear")
                        .HasColumnType("int")
                        .HasColumnName("production_year");

                    b.Property<int>("range")
                        .HasColumnType("int");

                    b.Property<string>("shortcut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("airplaneId");

                    b.ToTable("Airplane", "c");
                });

            modelBuilder.Entity("project.Models.Arrival", b =>
                {
                    b.Property<int>("arrivalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("arrival_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("airport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("airportShortcut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("airport_shortcut");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("arrivalId");

                    b.ToTable("Arrival", "c");
                });

            modelBuilder.Entity("project.Models.Departure", b =>
                {
                    b.Property<int>("departureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("arrival_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("airport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("airportShortcut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("airport_shortcut");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("departureId");

                    b.ToTable("Departure", "c");
                });

            modelBuilder.Entity("project.Models.Flight", b =>
                {
                    b.Property<int>("flightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flight_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("airportTax")
                        .HasColumnType("float")
                        .HasColumnName("airport_tax");

                    b.Property<double>("fixedCost")
                        .HasColumnType("float")
                        .HasColumnName("fixed_cost");

                    b.Property<string>("flightNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("flight_number");

                    b.HasKey("flightId");

                    b.ToTable("Flight", "c");
                });
#pragma warning restore 612, 618
        }
    }
}
